# Usa una imagen de Node
FROM node:18

# Crea el directorio de la aplicación
WORKDIR /app

# Instala las dependencias
COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto para el servidor de Angular
EXPOSE 4200
EXPOSE 4201

# Comando para iniciar la aplicación en modo de desarrollo
# CMD ["ng", "serve", "--host", "0.0.0.0"]

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=2000"]